package com.glintech.keyaoProject.model;

import java.util.Date;

// Generated 2016-8-12 14:22:12 by Hibernate Tools 3.2.2.GA

/**
 * Role generated by hbm2java
 */
public class Log implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String logId;
	private String pmpCode;
	private String userName;
	private String logName;
	private Date createTime;
	public Log(){
	}
	public Log(String logId, String pmpCode, String userName,
			String logName, Date createTime) {
		this.logId = logId;
		this.pmpCode = pmpCode;
		this.userName = userName;
		this.logName = logName;
		this.createTime = createTime;
	}
	public String getLogId() {
		return logId;
	}
	public void setLogId(String logId) {
		this.logId = logId;
	}
	public String getPmpCode() {
		return pmpCode;
	}
	public void setPmpCode(String pmpCode) {
		this.pmpCode = pmpCode;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getLogName() {
		return logName;
	}
	public void setLogName(String logName) {
		this.logName = logName;
	}
	public Date getCreateTime() {
		return createTime;
	}
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}
