package com.glintech.keyaoProject.model;

import java.util.HashSet;
import java.util.Set;

// Generated 2016-8-15 13:33:45 by Hibernate Tools 3.2.2.GA

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String projectId;
	private Pmp pmp;
	private String goodsImg1;
	private String goodsImg2;
	private String goodsImg3;
	private String goodsImg4;
	private String goodsAccessory;
	private String goodsDescription;
	private String partImg1;
	private String partImg2;
	private String partImg3;
	private String partImg4;
	private String partAccessory;
	private String partDescription;
	private String inferiorImg1;
	private String inferiorImg2;
	private String inferiorImg3;
	private String inferiorImg4;
	private String inferiorAccessory;
	private String inferiorDescription;
	private String speedImg1;
	private String speedImg2;
	private String speedImg3;
	private String speedImg4;
	private String speedAccessory;
	private String speedDescription;
	private String precisionImg1;
	private String precisionImg2;
	private String precisionImg3;
	private String precisionImg4;
	private String precisionAccessory;
	private String precisionDescription;
	private String environmentImg1;
	private String environmentImg2;
	private String environmentImg3;
	private String environmentImg4;
	private String environmentAccessory;
	private String environmentDescription;
	private String accessory;
	private String remark;
	private Set<Accessory> accessorys = new HashSet<Accessory>(0);
	
	public Project() {
	}

	public Project(String projectId) {
		this.projectId = projectId;
	}

	public Project(String projectId, Pmp pmp, String goodsImg1,
			String goodsImg2, String goodsImg3, String goodsImg4,
			String goodsAccessory, String goodsDescription, String partImg1,
			String partImg2, String partImg3, String partImg4,
			String partAccessory, String partDescription, String inferiorImg1,
			String inferiorImg2, String inferiorImg3, String inferiorImg4,
			String inferiorAccessory, String inferiorDescription,
			String speedImg1, String speedImg2, String speedImg3,
			String speedImg4, String speedAccessory, String speedDescription,
			String precisionImg1, String precisionImg2, String precisionImg3,
			String precisionImg4, String precisionAccessory,
			String precisionDescription, String environmentImg1,
			String environmentImg2, String environmentImg3,
			String environmentImg4, String environmentAccessory,
			String environmentDescription, String accessory, String remark,Set<Accessory> accessorys) {
		this.projectId = projectId;
		this.pmp = pmp;
		this.goodsImg1 = goodsImg1;
		this.goodsImg2 = goodsImg2;
		this.goodsImg3 = goodsImg3;
		this.goodsImg4 = goodsImg4;
		this.goodsAccessory = goodsAccessory;
		this.goodsDescription = goodsDescription;
		this.partImg1 = partImg1;
		this.partImg2 = partImg2;
		this.partImg3 = partImg3;
		this.partImg4 = partImg4;
		this.partAccessory = partAccessory;
		this.partDescription = partDescription;
		this.inferiorImg1 = inferiorImg1;
		this.inferiorImg2 = inferiorImg2;
		this.inferiorImg3 = inferiorImg3;
		this.inferiorImg4 = inferiorImg4;
		this.inferiorAccessory = inferiorAccessory;
		this.inferiorDescription = inferiorDescription;
		this.speedImg1 = speedImg1;
		this.speedImg2 = speedImg2;
		this.speedImg3 = speedImg3;
		this.speedImg4 = speedImg4;
		this.speedAccessory = speedAccessory;
		this.speedDescription = speedDescription;
		this.precisionImg1 = precisionImg1;
		this.precisionImg2 = precisionImg2;
		this.precisionImg3 = precisionImg3;
		this.precisionImg4 = precisionImg4;
		this.precisionAccessory = precisionAccessory;
		this.precisionDescription = precisionDescription;
		this.environmentImg1 = environmentImg1;
		this.environmentImg2 = environmentImg2;
		this.environmentImg3 = environmentImg3;
		this.environmentImg4 = environmentImg4;
		this.environmentAccessory = environmentAccessory;
		this.environmentDescription = environmentDescription;
		this.accessory = accessory;
		this.remark = remark;
		this.accessorys=accessorys;
	}

	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	public Pmp getPmp() {
		return pmp;
	}

	public void setPmp(Pmp pmp) {
		this.pmp = pmp;
	}

	public String getGoodsImg1() {
		return this.goodsImg1;
	}

	public void setGoodsImg1(String goodsImg1) {
		this.goodsImg1 = goodsImg1;
	}

	public String getGoodsImg2() {
		return this.goodsImg2;
	}

	public void setGoodsImg2(String goodsImg2) {
		this.goodsImg2 = goodsImg2;
	}

	public String getGoodsImg3() {
		return this.goodsImg3;
	}

	public void setGoodsImg3(String goodsImg3) {
		this.goodsImg3 = goodsImg3;
	}

	public String getGoodsImg4() {
		return this.goodsImg4;
	}

	public void setGoodsImg4(String goodsImg4) {
		this.goodsImg4 = goodsImg4;
	}

	public String getGoodsAccessory() {
		return this.goodsAccessory;
	}

	public void setGoodsAccessory(String goodsAccessory) {
		this.goodsAccessory = goodsAccessory;
	}

	public String getGoodsDescription() {
		return this.goodsDescription;
	}

	public void setGoodsDescription(String goodsDescription) {
		this.goodsDescription = goodsDescription;
	}

	public String getPartImg1() {
		return this.partImg1;
	}

	public void setPartImg1(String partImg1) {
		this.partImg1 = partImg1;
	}

	public String getPartImg2() {
		return this.partImg2;
	}

	public void setPartImg2(String partImg2) {
		this.partImg2 = partImg2;
	}

	public String getPartImg3() {
		return this.partImg3;
	}

	public void setPartImg3(String partImg3) {
		this.partImg3 = partImg3;
	}

	public String getPartImg4() {
		return this.partImg4;
	}

	public void setPartImg4(String partImg4) {
		this.partImg4 = partImg4;
	}

	public String getPartAccessory() {
		return this.partAccessory;
	}

	public void setPartAccessory(String partAccessory) {
		this.partAccessory = partAccessory;
	}

	public String getPartDescription() {
		return this.partDescription;
	}

	public void setPartDescription(String partDescription) {
		this.partDescription = partDescription;
	}

	public String getInferiorImg1() {
		return this.inferiorImg1;
	}

	public void setInferiorImg1(String inferiorImg1) {
		this.inferiorImg1 = inferiorImg1;
	}

	public String getInferiorImg2() {
		return this.inferiorImg2;
	}

	public void setInferiorImg2(String inferiorImg2) {
		this.inferiorImg2 = inferiorImg2;
	}

	public String getInferiorImg3() {
		return this.inferiorImg3;
	}

	public void setInferiorImg3(String inferiorImg3) {
		this.inferiorImg3 = inferiorImg3;
	}

	public String getInferiorImg4() {
		return this.inferiorImg4;
	}

	public void setInferiorImg4(String inferiorImg4) {
		this.inferiorImg4 = inferiorImg4;
	}

	public String getInferiorAccessory() {
		return this.inferiorAccessory;
	}

	public void setInferiorAccessory(String inferiorAccessory) {
		this.inferiorAccessory = inferiorAccessory;
	}

	public String getInferiorDescription() {
		return this.inferiorDescription;
	}

	public void setInferiorDescription(String inferiorDescription) {
		this.inferiorDescription = inferiorDescription;
	}

	public String getSpeedImg1() {
		return this.speedImg1;
	}

	public void setSpeedImg1(String speedImg1) {
		this.speedImg1 = speedImg1;
	}

	public String getSpeedImg2() {
		return this.speedImg2;
	}

	public void setSpeedImg2(String speedImg2) {
		this.speedImg2 = speedImg2;
	}

	public String getSpeedImg3() {
		return this.speedImg3;
	}

	public void setSpeedImg3(String speedImg3) {
		this.speedImg3 = speedImg3;
	}

	public String getSpeedImg4() {
		return this.speedImg4;
	}

	public void setSpeedImg4(String speedImg4) {
		this.speedImg4 = speedImg4;
	}

	public String getSpeedAccessory() {
		return this.speedAccessory;
	}

	public void setSpeedAccessory(String speedAccessory) {
		this.speedAccessory = speedAccessory;
	}

	public String getSpeedDescription() {
		return this.speedDescription;
	}

	public void setSpeedDescription(String speedDescription) {
		this.speedDescription = speedDescription;
	}

	public String getPrecisionImg1() {
		return this.precisionImg1;
	}

	public void setPrecisionImg1(String precisionImg1) {
		this.precisionImg1 = precisionImg1;
	}

	public String getPrecisionImg2() {
		return this.precisionImg2;
	}

	public void setPrecisionImg2(String precisionImg2) {
		this.precisionImg2 = precisionImg2;
	}

	public String getPrecisionImg3() {
		return this.precisionImg3;
	}

	public void setPrecisionImg3(String precisionImg3) {
		this.precisionImg3 = precisionImg3;
	}

	public String getPrecisionImg4() {
		return this.precisionImg4;
	}

	public void setPrecisionImg4(String precisionImg4) {
		this.precisionImg4 = precisionImg4;
	}

	public String getPrecisionAccessory() {
		return this.precisionAccessory;
	}

	public void setPrecisionAccessory(String precisionAccessory) {
		this.precisionAccessory = precisionAccessory;
	}

	public String getPrecisionDescription() {
		return this.precisionDescription;
	}

	public void setPrecisionDescription(String precisionDescription) {
		this.precisionDescription = precisionDescription;
	}

	public String getEnvironmentImg1() {
		return this.environmentImg1;
	}

	public void setEnvironmentImg1(String environmentImg1) {
		this.environmentImg1 = environmentImg1;
	}

	public String getEnvironmentImg2() {
		return this.environmentImg2;
	}

	public void setEnvironmentImg2(String environmentImg2) {
		this.environmentImg2 = environmentImg2;
	}

	public String getEnvironmentImg3() {
		return this.environmentImg3;
	}

	public void setEnvironmentImg3(String environmentImg3) {
		this.environmentImg3 = environmentImg3;
	}

	public String getEnvironmentImg4() {
		return this.environmentImg4;
	}

	public void setEnvironmentImg4(String environmentImg4) {
		this.environmentImg4 = environmentImg4;
	}

	public String getEnvironmentAccessory() {
		return this.environmentAccessory;
	}

	public void setEnvironmentAccessory(String environmentAccessory) {
		this.environmentAccessory = environmentAccessory;
	}

	public String getEnvironmentDescription() {
		return this.environmentDescription;
	}

	public void setEnvironmentDescription(String environmentDescription) {
		this.environmentDescription = environmentDescription;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<Accessory> getAccessorys() {
		return accessorys;
	}

	public void setAccessorys(Set<Accessory> accessorys) {
		this.accessorys = accessorys;
	}

}
