package com.glintech.keyaoProject.model;

import java.util.HashSet;
import java.util.Set;

// Generated 2016-8-12 14:22:12 by Hibernate Tools 3.2.2.GA

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private String roleId;
	private String name;
	private String memo;
	private Set<User> users = new HashSet<User>(0);

	public Role() {
	}

	public Role(String roleId) {
		this.roleId = roleId;
	}

	public Role(String roleId, String name, String memo, Set<User> users) {
		this.roleId = roleId;
		this.name = name;
		this.memo = memo;
		this.users = users;
	}

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Set<User> getUsers() {
		return users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
