package com.glintech.keyaoProject.model;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;

// Generated 2016-8-12 14:22:12 by Hibernate Tools 3.2.2.GA

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private String userId;
	private Role role;
	private String userName;
	private String name;
	private String password;
	private String phoneNumber;
	private String EMail;
	private String status;
	private Set<Pmp> pmps = new HashSet<Pmp>(0);
	private Set<Supplier> suppliers = new HashSet<Supplier>(0);
	public User() {
	}

	public User(String userId, Role role, String userName, String name,
			String password, String phoneNumber, String EMail,String status,
			Set<Pmp> pmps,Set<Supplier> suppliers) {
		this.userId = userId;
		this.role = role;
		this.userName = userName;
		this.name = name;
		this.password = password;
		this.phoneNumber = phoneNumber;
		this.EMail = EMail;
		this.status=status;
		this.pmps = pmps;
		this.suppliers = suppliers;
	}

	public Set<Pmp> getPmps() {
		return pmps;
	}

	public void setPmps(Set<Pmp> pmps) {
		this.pmps = pmps;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getEMail() {
		return this.EMail;
	}

	public void setEMail(String EMail) {
		this.EMail = EMail;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set<Pmp> getpmps() {
		return pmps;
	}

	public void setpmps(Set<Pmp> pmps) {
		this.pmps = pmps;
	}

	public Set<Supplier> getSuppliers() {
		return suppliers;
	}

	public void setSuppliers(Set<Supplier> suppliers) {
		this.suppliers = suppliers;
	}

}
